### PR TITLE
fix: Read data length from data type

### PR DESCRIPTION
**Pull request by Blackclaws**
For opaque types we read the data length from the type if read as a byte array

Fixes issue #105

### CODE REVIEW

**Comment by Blackclaws** [comment]
As discussed in the linked issue the underlying issue is that PureHDF writes opaque data in compact format, which is readable by other libraries but apparently PureHDF can't _read_ opaque data in compact format unless explicitly given the length of the data.

This _should_ have no other impacts but maybe there is a better place for this fix.

I've also added a round trip test to catch issues with round tripping opaque data in the future.

**Comment by Apollo3zehn** [comment]
Thank you :-) Probably I will be able to have a more detailed look on it on Thursday.

**Comment by Blackclaws** [comment]
This still does not work for Memory<byte> as the way that is constructed doesn't seem to work with anything but single bytes anyway. Not sure if that is tested anywhere right now but I've commented out the relevant test section and added a TODO.

**Comment by Apollo3zehn** [comment]
I had a look into the problem and found it to be a more general one and not only related to opaque datasets. I recently implemented the `raw mode` concept which allows the user to get raw data (`byte[]` or `Memory<byte>`) and I created the following unit tests for this feature:

- `CanRead_Raw_ByteArray`
- `CanRead_Raw_Memory`
- `CanRead_Raw_Span`

But those tests always used the method overload which accepts a buffer. When using this overload, the memory dimensions are well defined and the problem does not occur. However the `raw mode` is also active without the use of that method overload but this code path was not covered by the tests.

I extended the tests to close that gap and replicated the code changes in `NativeDataset` to the `HsdsDataset` to keep them similar.

Since the problem is not only relevant for opaque datasets, I had to remove the explicit check for it. Some code has been added to also support the `Memory<byte>` case.

So I think everything is covered now and ready for merge. Thanks for your efforts! Tomorrow I will work on support for symbolic links and also on further performance improvements and release a new version probably in the evening.

**Pull request merged**
